apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  api
  namespace: three-tier
  labels:
    name:  api
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  api
    spec:
      containers:
      - image:  911264217807.dkr.ecr.us-east-1.amazonaws.com/webapp/backend
        name:  frontend-image
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 3500
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 3500
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
          - name: MONGO_CONN_STR
            value: mongodb://mongodb-svc:27017/todo?directConnection=true
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: password       
        ports:
        - containerPort:  3500
          name:  api
      restartPolicy: Always
      imagePullPolicy: Always