apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  frontend-deployment
  namespace: three-tier
  labels:
    name:  frontend-deployment
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  frontend-deployment
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        image: 911264217807.dkr.ecr.us-east-1.amazonaws.com/webapp/frontend
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: ""
        ports:
        - containerPort: 3000